using System;
using System.Collections.Generic;
using System.Text;

namespace Tarot_Reader___Side_project.Minor_Arcana
{
    public class Pentacles
    {
        List<string> suitOfPentacles = new List<string>()
        {
            "ACE OF PENTACLES", "TWO OF PENTACLES", "THREE OF PENTACLES",
            "FOUR OF PENTACLES", "FIVE OF PENTACLES", "SIX OF PENTACLES",
            "SEVEN OF PENTACLE", "EIGHT OF PENTACLES", "NINE OF PENTACLES",
            "TEN OF PENTACLES", "PAGE OF PENTACLES", "KNIGHT OF PENTACLES",
            "QUEEN OF PENTACLES", "KING OF PENTACLES",

            "ACE OF PENTACLES REVERSED", "TWO OF PENTACLES REVERSED", "THREE OF PENTACLES REVERSED",
            "FOUR OF PENTACLES REVERSED", "FIVE OF PENTACLES REVERSED", "SIX OF PENTACLES REVERSED",
            "SEVEN OF PENTACLE REVERSED", "EIGHT OF PENTACLES REVERSED", "NINE OF PENTACLES REVERSED",
            "TEN OF PENTACLES REVERSED", "PAGE OF PENTACLES REVERSED", "KNIGHT OF PENTACLES REVERSED",
            "QUEEN OF PENTACLES REVERSED", "KING OF PENTACLES REVERSED"
        };
        List<string> suitOfPentaclesUp = new List<string>()
        {
            "ACE OF PENTACLES", "TWO OF PENTACLES", "THREE OF PENTACLES",
            "FOUR OF PENTACLES", "FIVE OF PENTACLES", "SIX OF PENTACLES",
            "SEVEN OF PENTACLE", "EIGHT OF PENTACLES", "NINE OF PENTACLES",
            "TEN OF PENTACLES", "PAGE OF PENTACLES", "KNIGHT OF PENTACLES",
            "QUEEN OF PENTACLES", "KING OF PENTACLES"
        };
        List<string> suitOfPentaclesRev = new List<string>()
        {
            "ACE OF PENTACLES REVERSED", "TWO OF PENTACLES REVERSED", "THREE OF PENTACLES REVERSED",
            "FOUR OF PENTACLES REVERSED", "FIVE OF PENTACLES REVERSED", "SIX OF PENTACLES REVERSED",
            "SEVEN OF PENTACLE REVERSED", "EIGHT OF PENTACLES REVERSED", "NINE OF PENTACLES REVERSED",
            "TEN OF PENTACLES REVERSED", "PAGE OF PENTACLES REVERSED", "KNIGHT OF PENTACLES REVERSED",
            "QUEEN OF PENTACLES REVERSED", "KING OF PENTACLES REVERSED"
        };
    }
}
