use master
go

drop database if exists Mystic_Managed;
go

create database Mystic_Managed;
go

use Mystic_Managed;
go

Begin Transaction

create table Cards (
	id int identity(1,1) primary key,
	name nvarchar (100) NOT NULL,
	arcana nvarchar(20) NOT NULL,
	as_situation nvarchar (max),
	as_obstacle nvarchar (max),
	as_advice nvarchar (max),
	as_situation_rev nvarchar (max),
	as_obstacle_rev nvarchar (max),
	as_advice_rev nvarchar (max),

	CONSTRAINT [UQ_name] unique ([name])
	);
GO



insert into Cards(name, arcana,
				as_situation, as_situation_rev,
				as_obstacle, as_obstacle_rev,
				as_advice, as_advice_rev)
values
					('The Fool', 'Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Magician', 'Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The High Priestess','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Empress','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Emperor','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Hierophant','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Lovers','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Chariot','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Strength','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Hermit','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Wheel Of Fortune','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Justice','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Hanged Man','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Death','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Temperance','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Devil','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Tower','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Star','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Moon','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The Sun','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Judgement','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('The World','Major',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
--------------------------------------------------------
--------------------------------------------------------
--------------------------------------------------------
		('Ace Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Two Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Three Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Four Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Five Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Six Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Seven Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Eight Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Nine Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Ten Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Page Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Knight Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Queen Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('King Of Cups','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
----------------------------------------------------
		('Ace Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Two Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Three Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Four Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Five Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Six Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Seven Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Eight Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Nine Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Ten Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Page Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Knight Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Queen Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('King Of Swords','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
---------------------------------------------------
		('Ace Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Two Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Three Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Four Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Five Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Six Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Seven Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Eight Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Nine Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Ten Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Page Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Knight Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Queen Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('King Of Pentacles','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
---------------------------------------------------------------
		('Ace Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Two Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Three Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Four Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Five Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Six Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Seven Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Eight Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Nine Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Ten Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Page Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Knight Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('Queen Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		''),
		('King Of Wands','Minor',
/*situation*/		'',
/*situation_rev*/	'',
/*obstacle*/		'',
/*obstacle_rev*/	'',
/*advice*/			'',
/*advice_rev*/		'');

Go



Commit Transaction
